import type { AssetDetail, AssetInventoryRow, AssetQueueItem } from "./asset-health.types.js";

const now = new Date("2026-03-30T09:00:00Z");
const daysAgo = (d: number) => new Date(now.valueOf() - d * 24 * 60 * 60 * 1000).toISOString();

export const assetFixtureInventory: AssetInventoryRow[] = [
  {
    id: "fixture-device-001",
    name: "LAPTOP-BCLARKE",
    ownerName: "Beth Clarke",
    ownerEmail: "beth.clarke@contoso.local",
    department: "Finance",
    site: "HQ",
    operatingSystem: "Windows 11 Pro",
    lastCheckInAt: daysAgo(21),
    encryptionStatus: "missing",
    antivirusStatus: "healthy",
    patchStatus: "missing",
    diskFreePercent: 12,
    deviceAgeDays: 1920,
    supportStatus: "warning",
    riskScore: 94,
    riskLevel: "critical",
    queueRank: 1,
    freshnessState: "stale",
    summary: "No encryption, out of patch window, and check-in stale for 21 days",
    signals: [
      { code: "missing_encryption", severity: "critical", label: "No encryption", explanation: "BitLocker is not enabled on this device." },
      { code: "stale_check_in", severity: "high", label: "Stale check-in", explanation: "Device has not checked in for 21 days." },
      { code: "missing_patch", severity: "high", label: "Patch overdue", explanation: "Device is outside the required patch window." },
      { code: "low_disk", severity: "medium", label: "Low disk space", explanation: "Less than 15% free disk space remaining." },
    ],
    complianceState: "noncompliant",
  },
  {
    id: "fixture-device-002",
    name: "DESKTOP-RMOORE",
    ownerName: "Ryan Moore",
    ownerEmail: "ryan.moore@contoso.local",
    department: "IT",
    site: "Branch",
    operatingSystem: "Windows 10 Pro",
    lastCheckInAt: daysAgo(3),
    encryptionStatus: "healthy",
    antivirusStatus: "missing",
    patchStatus: "missing",
    diskFreePercent: 34,
    deviceAgeDays: 2580,
    supportStatus: "missing",
    riskScore: 81,
    riskLevel: "critical",
    queueRank: 2,
    freshnessState: "healthy",
    summary: "Antivirus absent, OS nearing end of support, device is over 7 years old",
    signals: [
      { code: "missing_antivirus", severity: "critical", label: "No antivirus", explanation: "No antivirus agent detected on this device." },
      { code: "unsupported_os", severity: "high", label: "OS end of support", explanation: "Windows 10 reaches end of support in October 2025." },
      { code: "old_device", severity: "medium", label: "Ageing hardware", explanation: "Device is over 7 years old and may not meet security baseline." },
      { code: "missing_patch", severity: "high", label: "Patch overdue", explanation: "Device is outside the required patch window." },
    ],
    complianceState: "noncompliant",
  },
  {
    id: "fixture-device-003",
    name: "LAPTOP-JSMITH",
    ownerName: "James Smith",
    ownerEmail: "james.smith@contoso.local",
    department: "Sales",
    site: "HQ",
    operatingSystem: "Windows 11 Pro",
    lastCheckInAt: daysAgo(1),
    encryptionStatus: "healthy",
    antivirusStatus: "healthy",
    patchStatus: "missing",
    diskFreePercent: 8,
    deviceAgeDays: 740,
    supportStatus: "healthy",
    riskScore: 62,
    riskLevel: "high",
    queueRank: 3,
    freshnessState: "healthy",
    summary: "Patch overdue and disk space critically low",
    signals: [
      { code: "missing_patch", severity: "high", label: "Patch overdue", explanation: "Device is outside the required patch window." },
      { code: "low_disk", severity: "high", label: "Critical disk space", explanation: "Less than 10% free disk space remaining." },
    ],
    complianceState: "noncompliant",
  },
  {
    id: "fixture-device-004",
    name: "LAPTOP-PATEL-T",
    ownerName: "Tara Patel",
    ownerEmail: "tara.patel@contoso.local",
    department: "HR",
    site: "HQ",
    operatingSystem: "Windows 11 Pro",
    lastCheckInAt: daysAgo(8),
    encryptionStatus: "healthy",
    antivirusStatus: "warning",
    patchStatus: "healthy",
    diskFreePercent: 41,
    deviceAgeDays: 510,
    supportStatus: "healthy",
    riskScore: 45,
    riskLevel: "high",
    queueRank: 4,
    freshnessState: "warning",
    summary: "Antivirus reporting a warning state, check-in slightly stale",
    signals: [
      { code: "missing_antivirus", severity: "medium", label: "Antivirus warning", explanation: "Antivirus agent is reporting a degraded state." },
      { code: "stale_check_in", severity: "low", label: "Check-in late", explanation: "Device has not checked in for 8 days." },
    ],
    complianceState: "noncompliant",
  },
  {
    id: "fixture-device-005",
    name: "LAPTOP-NGUY-D",
    ownerName: "David Nguyen",
    ownerEmail: "david.nguyen@contoso.local",
    department: "Engineering",
    site: "Remote",
    operatingSystem: "Windows 11 Pro",
    lastCheckInAt: daysAgo(2),
    encryptionStatus: "healthy",
    antivirusStatus: "healthy",
    patchStatus: "warning",
    diskFreePercent: 55,
    deviceAgeDays: 380,
    supportStatus: "healthy",
    riskScore: 28,
    riskLevel: "watch",
    queueRank: 5,
    freshnessState: "healthy",
    summary: "Patch is slightly behind the required window",
    signals: [
      { code: "missing_patch", severity: "low", label: "Patch behind schedule", explanation: "Device is within grace period but approaching the patch deadline." },
    ],
    complianceState: "compliant",
  },
  {
    id: "fixture-device-006",
    name: "LAPTOP-OKON-A",
    ownerName: "Amara Okon",
    ownerEmail: "amara.okon@contoso.local",
    department: "Finance",
    site: "HQ",
    operatingSystem: "Windows 11 Pro",
    lastCheckInAt: daysAgo(1),
    encryptionStatus: "healthy",
    antivirusStatus: "healthy",
    patchStatus: "healthy",
    diskFreePercent: 68,
    deviceAgeDays: 290,
    supportStatus: "healthy",
    riskScore: 8,
    riskLevel: "low",
    queueRank: 6,
    freshnessState: "healthy",
    summary: "All signals healthy",
    signals: [],
    complianceState: "compliant",
  },
  {
    id: "fixture-device-007",
    name: "DESKTOP-IT-SHARED",
    ownerName: null,
    ownerEmail: null,
    department: "IT",
    site: "HQ",
    operatingSystem: "Windows 11 Pro",
    lastCheckInAt: daysAgo(0),
    encryptionStatus: "healthy",
    antivirusStatus: "healthy",
    patchStatus: "healthy",
    diskFreePercent: 72,
    deviceAgeDays: 180,
    supportStatus: "healthy",
    riskScore: 5,
    riskLevel: "low",
    queueRank: 7,
    freshnessState: "healthy",
    summary: "All signals healthy — no assigned owner",
    signals: [
      { code: "data_incomplete", severity: "low", label: "No assigned owner", explanation: "This device has no owner assigned in Intune." },
    ],
    complianceState: "compliant",
  },
];

export const assetFixtureQueue: AssetQueueItem[] = assetFixtureInventory
  .filter((d): d is AssetInventoryRow & { riskScore: number; riskLevel: string; queueRank: number; summary: string; freshnessState: string } =>
    d.riskScore !== null && d.riskLevel !== null && d.queueRank !== null && d.summary !== null && d.freshnessState !== null
  )
  .map((d) => ({
    id: d.id,
    name: d.name,
    ownerName: d.ownerName,
    riskScore: d.riskScore!,
    riskLevel: d.riskLevel!,
    queueRank: d.queueRank!,
    summary: d.summary!,
    freshnessState: d.freshnessState!,
    signals: d.signals,
  }));

export const assetFixtureDetails: Record<string, AssetDetail> = Object.fromEntries(
  assetFixtureInventory.map((d) => [
    d.id,
    {
      ...d,
      serialNumber: `SN-${d.id.slice(-6).toUpperCase()}`,
      complianceState: d.riskLevel === "critical" ? "noncompliant" : d.riskLevel === "high" ? "noncompliant" : "compliant",
      sourceSystem: "seeded_example",
      sourceId: d.id,
      calculatedAt: daysAgo(0),
      complianceAssignments: [],
    },
  ])
);
