import type { LifecycleRunDetail } from "./lifecycle.types.js";

const base = new Date("2026-03-28T09:00:00Z");
const hoursAgo = (h: number) => new Date(base.valueOf() - h * 60 * 60 * 1000).toISOString();

export const lifecycleFixtureRuns: LifecycleRunDetail[] = [
  {
    id: "fixture-run-001",
    kind: "onboarding",
    templateKey: "employee-onboarding",
    templateVersion: 1,
    subjectDisplayName: "Alex Johnson",
    subjectEmail: "alex.johnson@contoso.local",
    requestedBy: "Dev Operator",
    status: "active",
    startedAt: hoursAgo(48),
    closedAt: null,
    updatedAt: hoursAgo(2),
    groups: [
      {
        key: "identity",
        title: "Identity & Access",
        position: 1,
        steps: [
          {
            key: "create-entra-account",
            title: "Create Entra ID account",
            instructions: "Create the user account in Microsoft Entra ID with the correct department and job title.",
            groupKey: "identity",
            position: 1,
            status: "manual",
            statusReason: null,
            note: "Account created, UPN: alex.johnson@contoso.local",
            ticketId: "INC-1041",
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: hoursAgo(46),
          },
          {
            key: "assign-license",
            title: "Assign Microsoft 365 license",
            instructions: "Assign the Microsoft 365 Business Premium license via the Entra admin portal.",
            groupKey: "identity",
            position: 2,
            status: "manual",
            statusReason: null,
            note: "M365 Business Premium assigned",
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: hoursAgo(45),
          },
          {
            key: "assign-groups",
            title: "Assign security groups",
            instructions: "Add user to the appropriate department group and any role-specific security groups.",
            groupKey: "identity",
            position: 3,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
      {
        key: "device",
        title: "Device Provisioning",
        position: 2,
        steps: [
          {
            key: "enroll-device",
            title: "Enrol device in Intune",
            instructions: "Set up the assigned laptop and complete the Intune enrolment wizard. Confirm device appears in the Intune portal.",
            groupKey: "device",
            position: 1,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
          {
            key: "verify-encryption",
            title: "Verify BitLocker encryption",
            instructions: "Confirm BitLocker is active and the recovery key has been escrowed to Entra ID.",
            groupKey: "device",
            position: 2,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
      {
        key: "follow-up",
        title: "Follow-up",
        position: 3,
        steps: [
          {
            key: "confirm-access",
            title: "Confirm user can sign in",
            instructions: "Have the new employee sign in and confirm access to email and key applications.",
            groupKey: "follow-up",
            position: 1,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
    ],
  },
  {
    id: "fixture-run-002",
    kind: "offboarding",
    templateKey: "employee-offboarding",
    templateVersion: 1,
    subjectDisplayName: "Sarah Chen",
    subjectEmail: "sarah.chen@contoso.local",
    requestedBy: "Dev Operator",
    status: "active",
    startedAt: hoursAgo(4),
    closedAt: null,
    updatedAt: hoursAgo(1),
    groups: [
      {
        key: "access",
        title: "Access Revocation",
        position: 1,
        steps: [
          {
            key: "disable-entra-account",
            title: "Disable Entra ID account",
            instructions: "Immediately disable the user account in Entra ID to prevent further sign-in.",
            groupKey: "access",
            position: 1,
            status: "manual",
            statusReason: null,
            note: "Account disabled at 08:12",
            ticketId: "INC-1058",
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: hoursAgo(3),
          },
          {
            key: "revoke-sessions",
            title: "Revoke active sessions",
            instructions: "Revoke all active Microsoft 365 and Entra ID sessions from the user portal.",
            groupKey: "access",
            position: 2,
            status: "manual",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: hoursAgo(3),
          },
          {
            key: "remove-groups",
            title: "Remove from security groups",
            instructions: "Remove the user from all security groups and distribution lists.",
            groupKey: "access",
            position: 3,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
      {
        key: "device",
        title: "Device Recovery",
        position: 2,
        steps: [
          {
            key: "remote-wipe",
            title: "Initiate remote wipe",
            instructions: "Issue a remote wipe command via Intune for all devices assigned to the user.",
            groupKey: "device",
            position: 1,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
      {
        key: "handoff",
        title: "Handoff & Data",
        position: 3,
        steps: [
          {
            key: "mailbox-handoff",
            title: "Configure mailbox handoff",
            instructions: "Set up an auto-reply and forward critical emails to the manager for 30 days.",
            groupKey: "handoff",
            position: 1,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
          {
            key: "onedrive-retention",
            title: "Preserve OneDrive files",
            instructions: "Transfer OneDrive ownership to the manager before the 30-day retention window closes.",
            groupKey: "handoff",
            position: 2,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
      {
        key: "follow-up",
        title: "Follow-up",
        position: 4,
        steps: [
          {
            key: "confirm-closure",
            title: "Confirm full offboarding closure",
            instructions: "Verify all access is removed and hardware has been returned or wiped.",
            groupKey: "follow-up",
            position: 1,
            status: "pending",
            statusReason: null,
            note: null,
            ticketId: null,
            assetId: null,
            mailboxRef: null,
            handoffRef: null,
            completedAt: null,
          },
        ],
      },
    ],
  },
];
